package io.papermc.proofreader.proofreader.service;

import io.papermc.proofreader.proofreader.github.GithubService;
import io.papermc.proofreader.proofreader.service.StateService.MainState;
import io.papermc.proofreader.proofreader.service.StateService.State;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.regex.Pattern;

import static io.papermc.proofreader.proofreader.ProofReaderConfig.Config;

@Service
public class CommentService {

    private static final Pattern checkboxPattern = Pattern.compile("(?m)^- \\[([ x])] (.+)$");
    private final GithubService github;
    private final Config config;

    public CommentService(GithubService github, Config config) {
        this.github = github;
        this.config = config;
    }

    void addOrUpdateProofReadingComment(State state) {
        if (state instanceof MainState) return;

        String comment;
        if (state.firstTimer && !state.approved) {
            comment = createWelcomeMessage(state);
        } else {
            comment = createProofReadingComment(state);
        }

        if (state.commentId != -1) {
            github.updateComment(state.commentId, comment);
        } else {
            state.commentId = github.addComment(state.prNumber, comment);
        }
    }

    private String createProofReadingComment(State state) {
        return """
                ## Reviewer Tools
                
                Status: %s  \s
                
                - [ ] Rebase PR
                - [ ] Force Update
                
                Browse patched branch: %s \s
                Open patched branch in VSC: %s \s
                Diff patched branch: %s  \s
                
                *This comment was generated by [ProofReader](https://github.com/PaperMC/ProofReader).*
                """.formatted(state.status,
                createdBrowseUrl(state),
                createdOpenUrl(state),
                createDiffsUrl(state));
    }

    private String createWelcomeMessage(State state) {
        return """
                ## Reviewer Tools
                
                Status: %s  \s
                
                - [ ] Approve for ProofReader
                
                *This comment was generated by [ProofReader](https://github.com/PaperMC/ProofReader).*
                """.formatted(state.status);
    }

    private String createdBrowseUrl(State state) {
        if (state.completed) return "pending";
        return "https://github.com/" + config.targetRepo().withSlash() + "/tree/" + state.branch;
    }

    private String createdOpenUrl(State state) {
        if (state.completed) return "pending";
        return "https://github.dev/" + config.targetRepo().withSlash() + "/tree/" + state.branch;
    }

    private String createDiffsUrl(State state) {
        if (state.completed) return "pending";
        return "https://diffs.dev/?github_url=https%3A%2F%2Fgithub.com%2F" + config.targetRepo().withEscapedSlash() + "%2Fcompare%2Fmain..." + state.branch;
    }

    public Set<String> newCheckedBoxes(String oldComment, String newComment) {
        var oldStatuses = checkboxStatus(oldComment);
        var newStatuses = checkboxStatus(newComment);
        var result = new HashSet<String>();

        for (var entry : newStatuses.entrySet()) {
            String label = entry.getKey();
            boolean newChecked = entry.getValue();
            boolean oldChecked = oldStatuses.getOrDefault(label, false);

            if (newChecked && !oldChecked) {
                result.add(label.toLowerCase(Locale.ROOT));
            }
        }

        return result;
    }

    private Map<String, Boolean> checkboxStatus(String input) {
        var result = new HashMap<String, Boolean>();
        var matcher = checkboxPattern.matcher(input);

        while (matcher.find()) {
            String label = matcher.group(2).trim();
            boolean checked = matcher.group(1).equals("x");
            result.put(label, checked);
        }

        return result;
    }
}
